// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOkOwxHG7PFUf6h3TfiWWS7_tLqHfb7E',
    appId: '1:224899509093:web:6ac1d09e46e35b2cbccf8c',
    messagingSenderId: '224899509093',
    projectId: 'smc-iot',
    authDomain: 'smc-iot.firebaseapp.com',
    databaseURL: 'https://smc-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smc-iot.appspot.com',
    measurementId: 'G-NL19JVX2FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7Ydutr4w29TtrABzWXEKxE7ePSFFEE0',
    appId: '1:224899509093:android:912dae58cc0b67ecbccf8c',
    messagingSenderId: '224899509093',
    projectId: 'smc-iot',
    databaseURL: 'https://smc-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smc-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5QI-TReVHeThWYK8sbTnd1SGqpJ31Lw',
    appId: '1:224899509093:ios:e386c7b05a529464bccf8c',
    messagingSenderId: '224899509093',
    projectId: 'smc-iot',
    databaseURL: 'https://smc-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smc-iot.appspot.com',
    iosClientId: '224899509093-tvsof8kfkifmle3kdgvdgumgns7sudeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smcIot',
  );
}
